In [1]:

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
import kagglehub
import pandas as pd
import os

# Download dataset
path = kagglehub.dataset_download("snap/amazon-fine-food-reviews")

print("Dataset Path:", path)
print("Files:", os.listdir(path))

# Load Reviews.csv
csv_path = os.path.join(path, "Reviews.csv")

df = pd.read_csv(csv_path, nrows=5000)

print(df.head())
print(df.shape)

100%|██████████| 242M/242M [02:35<00:00, 1.63MB/s] 

Extracting files...


Dataset Path: C:\Users\suhas\.cache\kagglehub\datasets\snap\amazon-fine-food-reviews\versions\2
Files: ['database.sqlite', 'hashes.txt', 'Reviews.csv']
   Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

      

In [6]:
light_reviews = df[df["Text"].str.contains(r"\blight\b", case=False, na=False)]

print("Total reviews containing 'light':", len(light_reviews))

# Display a few examples to manually choose sentences
for i, review in enumerate(light_reviews["Text"].head(20)):
    print(f"\nReview {i+1}:")
    print(review)

Total reviews containing 'light': 1415

Review 1:
This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.

Review 2:
A very delicate green tea with a smooth light taste and an subtle floral tones and no bitter aftertaste.<br /><br />In the 20+ years we have been drinking Ahmad teas not even once have we been disappointed. The superb quality of Ahmad teas has remained consistent throughout the years.<br /><br />I am so happy to find Ahmad teas available here (thanks Amazon!) because only a few stores carry it in my area and they are quite a 

In [10]:
sentence_1 = "This olive oil is wonderful and very light on the stomach."
sentence_2 = "The packaging was broken and let too much light inside the box."
sentence_3 = "I prefer this brand because it is a light and healthy snack."

sentences = [sentence_1, sentence_2, sentence_3]


In [11]:
vectorizer = CountVectorizer()

doc_term_matrix = vectorizer.fit_transform(sentences)

dense_matrix = doc_term_matrix.toarray()

print("\nDense Matrix:")
print(dense_matrix)

print("\nVocabulary:")
print(vectorizer.get_feature_names_out())


Dense Matrix:
[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]

Vocabulary:
['and' 'because' 'box' 'brand' 'broken' 'healthy' 'inside' 'is' 'it' 'let'
 'light' 'much' 'oil' 'olive' 'on' 'packaging' 'prefer' 'snack' 'stomach'
 'the' 'this' 'too' 'very' 'was' 'wonderful']


In [12]:
vectorizer = CountVectorizer()

doc_term_matrix = vectorizer.fit_transform(sentences)

dense_matrix = doc_term_matrix.toarray()

print("\nDense Matrix:")
print(dense_matrix)

print("\nVocabulary:")
print(vectorizer.get_feature_names_out())


Dense Matrix:
[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]

Vocabulary:
['and' 'because' 'box' 'brand' 'broken' 'healthy' 'inside' 'is' 'it' 'let'
 'light' 'much' 'oil' 'olive' 'on' 'packaging' 'prefer' 'snack' 'stomach'
 'the' 'this' 'too' 'very' 'was' 'wonderful']


In [13]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print("\nVector 1:", vec_1)
print("Vector 2:", vec_2)
print("Vector 3:", vec_3)


Vector 1: [1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
Vector 2: [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
Vector 3: [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [14]:
similarity_1_2 = np.dot(vec_1, vec_2)

similarity_1_3 = np.dot(vec_1, vec_3)

In [15]:
print("\n==============================")
print("Similarity Scores")
print("==============================")

print("Sentence 1 vs Sentence 2 :", similarity_1_2)
print("Sentence 1 vs Sentence 3 :", similarity_1_3)


Similarity Scores
Sentence 1 vs Sentence 2 : 4
Sentence 1 vs Sentence 3 : 4
